spring:
  application:
    name: mis-employee-service
    version: 2.0
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//192.168.100.100:1521/nwi
    username: mis_kopie
    password: mis_kopie

server:
  port: 8081    